### ISSUE TITLE
Invalid credential when first connection to Centreon Web interface

### ISSUE THREAD

**Issue by uc33260** [centreon-archive/centreon-archived#11278]
Hi team,

I installed Centreon 21.10 from ISO (CentOS).

But when I tried to connect to the web interface for the first time, I got this error message:
 
Invalid credentials

I’m sure to use the right password defined at the step 5 “Admin information.

Is that a known bug ?

How to reset this password ?

Thank you

**Comment by ponchoh** [comment]
moving chat to .. 

https://thewatch.centreon.com/platform-7/invalid-credential-when-first-connection-to-centreon-web-interface-752
