### ISSUE TITLE
Very long time to approve small PR

### ISSUE THREAD

**Issue by vhsantos** [centreon-archive/centreon-archived#11375]
### Feature explanation

Small and old PR should be revised and rejected/accepted quickly.

### Additional information

I have a very simple and small (with only one line) [PR](https://github.com/centreon/centreon/pull/10958) created many months ago.
Since then, many other PR have been approved and releases have been created.

What is the idea of having PR from the community if they aren't going to be revised ?? At least some feedback to the author like "We don't like your PR" or "Please, change this or this other" should be appreciated and certainly will encourage people to send more PR to this project.

**Comment by lpinsivy** [comment]
PR has been added into our backlog. Sorry for the delay
