### ISSUE TITLE
PHP Fatal error when importing Host with CLAPI 

### ISSUE THREAD

**Issue by NTIC94130** [centreon-archive/centreon-archived#11434]
Hello,

# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

For the RPM based systems

-- Copy/Paste the result of the following command --
```
$ rpm -qa | grep centreon | egrep -v "(plugin|pack)" | sort
```
centreon-22.04.0-2.el7.centos.noarch
centreon-auto-discovery-server-22.04.0-1.el7.centos.noarch
centreon-awie-22.04.0-1.el7.centos.noarch
centreon-broker-22.04.0-13.el7.x86_64
centreon-broker-cbd-22.04.0-13.el7.x86_64
centreon-broker-cbmod-22.04.0-13.el7.x86_64
centreon-broker-core-22.04.0-13.el7.x86_64
centreon-broker-storage-22.04.0-13.el7.x86_64
centreon-central-22.04.0-2.el7.centos.noarch
centreon-clib-22.04.0-13.el7.x86_64
centreon-common-22.04.0-2.el7.centos.noarch
centreon-connector-22.04.0-13.el7.x86_64
centreon-connector-perl-22.04.0-13.el7.x86_64
centreon-connector-ssh-22.04.0-13.el7.x86_64
centreon-database-22.04.0-2.el7.centos.noarch
centreon-engine-22.04.0-13.el7.x86_64
centreon-engine-daemon-22.04.0-13.el7.x86_64
centreon-engine-extcommands-22.04.0-13.el7.x86_64
centreon-gorgone-22.04.0-9.el7.centos.noarch
centreon-gorgone-centreon-config-22.04.0-9.el7.centos.noarch
centreon-license-manager-22.04.0-1.el7.centos.noarch
centreon-license-manager-common-22.04.0-1.el7.centos.noarch
centreon-perl-libs-22.04.0-2.el7.centos.noarch
centreon-poller-22.04.0-2.el7.centos.noarch
centreon-pp-manager-22.04.0-2.el7.centos.noarch
centreon-release-22.04-3.el7.centos.noarch
centreon-trap-22.04.0-2.el7.centos.noarch
centreon-web-22.04.0-2.el7.centos.noarch
centreon-widget-engine-status-22.04.0-5.el7.centos.noarch
centreon-widget-global-health-22.04.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-22.04.0-5.el7.centos.noarch
centreon-widget-grid-map-22.04.0-5.el7.centos.noarch
centreon-widget-hostgroup-monitoring-22.04.0-5.el7.centos.noarch
centreon-widget-host-monitoring-22.04.0-5.el7.centos.noarch
centreon-widget-httploader-22.04.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-22.04.0-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-22.04.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-22.04.0-5.el7.centos.noarch
centreon-widget-service-monitoring-22.04.0-5.el7.centos.noarch
centreon-widget-single-metric-22.04.0-5.el7.centos.noarch
centreon-widget-tactical-overview-22.04.0-5.el7.centos.noarch

For the deb based systems

-- Copy/Paste the result of the following command --
```
$ dpkg -l | grep centreon
```
***Operating System***

*CentOS

***Browser used***

- [ ] Google Chrome
- [ ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari
- [ x ] Edge

Version: --

***Additional environment details (AWS, VirtualBox, physical, etc.):***

VmWare ESXI - Vcenter 7

### Description

-- Describe the encountered issue --

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. ssh to srvcentreon2
2. Export clapi (clapi='centreon -u admin -p password')
clapi -e --select "HOST;CENTRALE_ARCHIVES" >Host_CENTRALE_ARCHIVES_27072022.txt
3. Suppress Host CENTRALE_ARCHIVES from Centreon
4. Import clapi
clapi -i Host_CENTRALE_ARCHIVES_27072022.txt

5. Got this error. The host is visible again in centreon but with none services attached and this fatal error in php

### Describe the received result
Line 1 : Object already exists (CENTRALE_ARCHIVES)
Line 2 : Object already exists (24x7)
Line 36 : Object already exists (admin)
Line 57 : Object already exists (generic-active-host-custom)
Line 74 : Object already exists (generic-active-host)
Line 75 : Object already exists (base_host_alive)
Line 102 : Object already exists
Line 125 : Object already exists
Line 149 : Object already exists
Line 150 : Object already exists (base_centreon_ping)
PHP Fatal error:  Uncaught Error: Class "Centreon_Object_Service_Macro_Custom" not found in /usr/share/centreon/www/class/centreon-clapi/centreonServiceTemplate.class.php:698
Stack trace:
#0 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(852): CentreonClapi\CentreonServiceTemplate->setmacro()
#1 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(815): CentreonClapi\CentreonAPI->launchActionForImport()
#2 /usr/share/centreon/bin/centreon(196): CentreonClapi\CentreonAPI->import()
#3 {main}
  thrown in /usr/share/centreon/www/class/centreon-clapi/centreonServiceTemplate.class.php on line 698

### Describe the expected result
View the Host in Centreon with all services attached.

### Logs

**PHP error logs**

For version using PHP 7.2 or 7.3 on centOs 8 or PHP 8
```
tail -f /var/log/php-fpm/centreon-error.log : 

I have no centreon-error.log , only a file named error.log

[27-Jul-2022 14:49:09] NOTICE: Terminating ...
[27-Jul-2022 14:49:09] NOTICE: exiting, bye-bye!
[27-Jul-2022 14:49:40] NOTICE: fpm is running, pid 1098
[27-Jul-2022 14:49:40] NOTICE: ready to handle connections
[27-Jul-2022 14:49:40] NOTICE: systemd monitor interval set to 10000ms
[27-Jul-2022 14:56:38] NOTICE: Terminating ...
[27-Jul-2022 14:56:38] NOTICE: exiting, bye-bye!
[27-Jul-2022 14:57:19] NOTICE: fpm is running, pid 1143
[27-Jul-2022 14:57:19] NOTICE: ready to handle connections
[27-Jul-2022 14:57:19] NOTICE: systemd monitor interval set to 10000ms
For version using PHP 7.3 on centOs 7
```
tail -f /var/opt/rh/rh-php73/log/php-fpm/centreon-error.log
```
For version using PHP 7.2 on centOs 7
```
tail -f /var/opt/rh/rh-php72/log/php-fpm/centreon-error.log
```

**centreon-engine logs (*if needed*)**

```
tail -f /var/log/centreon-engine/centengine.log
```
[1658927470] [2331] Event loop start at Wed Jul 27 15:11:10 2022
[1658927470] [2331] Configuration loaded, main loop starting.
[1658927548] [2331] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;Centeon-central;proc-centreontrapd;1658927547
[1658927550] [2331] SERVICE ALERT: Centeon-central;proc-centreontrapd;CRITICAL;SOFT;1;CRITICAL: Number of current processes running: 0
[1658927610] [2331] SERVICE ALERT: Centeon-central;proc-centreontrapd;CRITICAL;SOFT;2;CRITICAL: Number of current processes running: 0
[1658927670] [2331] SERVICE ALERT: Centeon-central;proc-centreontrapd;CRITICAL;HARD;3;CRITICAL: Number of current processes running: 0
[1658927670] [2331] SERVICE NOTIFICATION: Admin_NTIC;Centeon-central;proc-centreontrapd;CRITICAL;host-notify-by-email;CRITICAL: Number of current processes running: 0
[1658927670] [2331] SERVICE NOTIFICATION: Admin_NTIC;Centeon-central;proc-centreontrapd;CRITICAL;service-notify-by-email;CRITICAL: Number of current processes running: 0
[1658930035] [2331] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;Centeon-central;proc-centreontrapd;1658930033
[1658930746] [2331] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;Centeon-central;proc-centreontrapd;1658930743
**centreon-broker logs (*if needed*)**

```
tail -f /var/log/centreon-broker/central-broker-master.log
```
[2022-07-27T16:30:19.113+02:00] [core] [info] feeder: thread of client 'central-broker-master-input-4' will exit
[2022-07-27T16:30:19.306+02:00] [core] [info] New incoming connection 'central-broker-master-input-5'
[2022-07-27T16:30:19.308+02:00] [core] [info] multiplexing: 'central-broker-master-input-5' starts with 0 in queue and the queue file is disable
[2022-07-27T16:30:19.311+02:00] [core] [info] removing 'central-broker-master-input-4' from acceptor 'central-broker-master-input'
[2022-07-27T16:30:19.311+02:00] [core] [info] Destroying muxer central-broker-master-input-4: number of events in the queue: 0
[2022-07-27T16:30:20.400+02:00] [core] [info] main: configuration update requested
[2022-07-27T16:30:20.401+02:00] [core] [info] modules: attempt to load '/usr/share/centreon/lib/centreon-broker/50-tcp.so' which is already loaded
[2022-07-27T16:30:20.401+02:00] [core] [info] modules: attempt to load '/usr/share/centreon/lib/centreon-broker/20-unified_sql.so' which is already loaded
[2022-07-27T16:30:20.401+02:00] [core] [info] modules: attempt to load '/usr/share/centreon/lib/centreon-broker/15-stats.so' which is already loaded
[2022-07-27T16:30:20.401+02:00] [core] [info] multiplexing: engine started

**centreon gorgone logs for Centreon >= 20.4  (*if needed*)**

```
tail -f /var/log/centreon-gorgone/gorgoned.log
```
**centcore logs for Centreon <= 19.10.x (*if needed*)**

```
tail -f /var/log/centreon/centcore.log
```

### Additional relevant information (e.g. frequency, ...)
[Host_CENTRALE_ARCHIVES_27072022.txt](https://github.com/centreon/centreon/files/9200215/Host_CENTRALE_ARCHIVES_27072022.txt)

**Comment by proxyconcept** [comment]
I have the same error with 22.04.1 when I'm trying to re-import my export.

It seems that some `requires` are missing in centreonServiceTemplate.class.php

I can solve this error by adding this:
```diff
diff -rub a/centreon/www/class/centreon-clapi/centreonServiceTemplate.class.php b/centreon/www/class/centreon-clapi/centreonServiceTemplate.class.php
--- a/centreon/www/class/centreon-clapi/centreonServiceTemplate.class.php	2022-07-29 17:05:24.424662300 +0200
+++ b/centreon/www/class/centreon-clapi/centreonServiceTemplate.class.php	2022-07-29 17:07:11.073089341 +0200
@@ -41,6 +41,7 @@
 require_once "Centreon/Object/Relation/Service/Template/Host.php";
 require_once "Centreon/Object/Host/Template.php";
 require_once "Centreon/Object/Service/Template.php";
+require_once "Centreon/Object/Service/Macro/Custom.php";
 
 /**
  * Class for managing service templates
```

**Comment by proxyconcept** [comment]
But this class disturbs me... I have some other imports which fail very oddly!

For example it works if I import a file with only this line (assuming I already have a service template named "default_notification"):
```
STPL;addcontactgroup;default_notification;Guest
```

But the same line failed to import if I have before another line on CONTACT or CONTACTTPL:
```
CONTACT;ADD;Notify-by-email-workhours;Notify-by-email-workhours;mail@example.org;p4ssw0rd@TEST;0;1;browser;local
STPL;addcontactgroup;default_notification;Guest
```
It looks once again a missing require:
```
PHP Fatal error:  Uncaught Error: Class "Centreon_Object_Service" not found in /usr/share/centreon/www/class/centreon-clapi/centreonServiceTemplate.class.php:88
Stack trace:
#0 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(980): CentreonClapi\CentreonServiceTemplate->__construct()
#1 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(845): CentreonClapi\CentreonAPI->iniObject()
#2 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(815): CentreonClapi\CentreonAPI->launchActionForImport()
#3 /usr/share/centreon/bin/centreon(196): CentreonClapi\CentreonAPI->import()
#4 {main}
  thrown in /usr/share/centreon/www/class/centreon-clapi/centreonServiceTemplate.class.php on line 88
```

I can solve it by adding:
```php
require_once "Centreon/Object/Service/Service.php";
```

But it's very strange that this missing require is a not a problem when I import only this line! I don't really understand how dependencies and class loader is working, but it would have been more logical that the require is missing when dealing with only this import, not the inverse.

**Comment by proxyconcept** [comment]
I think that I have found the real origin of the problems: just remove the "require bootstrap" from centreonContact and it's not necessary to add anymore requires in others classes (see the PR)

**Comment by proxyconcept** [comment]
Well, no... It would have been too easy!

The "require bootstrap.php" is necessary in other case...

**Comment by proxyconcept** [comment]
Sounds good to me with this new PR

**Comment by kduret** [comment]
Hi !
This is fixed here by https://github.com/centreon/centreon/pull/11492
