### ISSUE TITLE
README is not up to date

### ISSUE THREAD

**Issue by mayrstefan** [centreon-archive/centreon-archived#11584]
# BUG REPORT INFORMATION

[README](https://github.com/centreon/centreon/blob/develop/README.md) is not up to date:

1. the link to [Using the ISO](https://docs.centreon.com/current/en/installation/installation-of-a-central-server/using-centreon-iso.html) is broken
2. the mentioned supported versions are one version behind the current status

**Comment by ponchoh** [comment]
an option

https://docs.centreon.com/docs/21.10/installation/installation-of-a-central-server/using-centreon-iso/

**Comment by mayrstefan** [comment]
@ponchoh  this is for 21.10 - that page doesn't exist in the current documentation any more. So for 22.04 either the link is wrong or the docs are incomplete

**Comment by ponchoh** [comment]
@mayrstefan I was thinking you can use it as a reference, I am currently under the impression that there will not be an ISO for 22+ and I've created a PR to remove them 

https://github.com/centreon/centreon/pull/11592

Thank you
👍
