### ISSUE TITLE
Custom views - poller field now mandatory

### ISSUE THREAD

**Issue by martinpiny** [centreon-archive/centreon-archived#11616]
Hello,

I see now through all new versions of Centreon, that in custom views is poller field mandatory.
This makes me no sense, as views should be used for some centralized overview, and now with that logic change. it stopped working.

Is this kind of bug or feature? It was not described in the changelogs.

Older versions
![custom_views_old](https://user-images.githubusercontent.com/93271059/186595794-c20c6c47-c3ed-4054-8de2-fb2bbccaf1ac.png)

New versions (21.04.15? +)

![custom_views_new](https://user-images.githubusercontent.com/93271059/186595950-0719a0a5-abee-4a6f-bb27-87bdd5ed70b8.png)

I would appreciate your help in this matter.

Regards,
Martin.

**Comment by ponchoh** [comment]
# 👋

https://github.com/centreon/centreon/pull/11317/commits/50bb6a97cf847ce3ba793b67147b9a580e438287

## 🤞
