### ISSUE TITLE
[22.04.2] Reload ACL - refresh icons out of the table

### ISSUE THREAD

**Issue by kozfelipe** [centreon-archive/centreon-archived#11625]
***Browser used***

- [x] Google Chrome

### Description

The user's refresh icons are being displayed out of the table with no click function.
No javascript errors reported by console

![image](https://user-images.githubusercontent.com/25208457/186701933-5e843cb2-f40c-4e79-89ce-dec72d43690e.png)

**Comment by ponchoh** [comment]
same on 🔥🦊

![image](https://user-images.githubusercontent.com/85764737/196543692-ff953704-89f0-48b6-94ae-0c17a3ec30df.png)
