### ISSUE TITLE
[22.04.2] CLAPI Service Add - Object not Found

### ISSUE THREAD

**Issue by kozfelipe** [centreon-archive/centreon-archived#11630]
Hi there,

I am not able to add a service using CLAPI in 22.04

```
centreon -u admin -p centreon -o service -a add -v "localhost;test;"                                                 
Object not found:
```
I can add hosts normally tho

**Comment by ponchoh** [comment]
# Add:

```
centreon -u uuuu -p 'xxx' -o SERVICE -a add -v "Central;random_name;generic-active-service-custom" 
```

## docs

https://docs.centreon.com/docs/api/clapi/#add-19

![image](https://user-images.githubusercontent.com/85764737/186987170-e70b341a-e90d-48c3-9e27-3e96dcfb8685.png)

### from your data

```
centreon -u admin -p centreon -o service -a add -v "localhost;test;"                                                 
Object not found:
```

1.localhost
2.test
3.?

# 🥳
continues @ https://thewatch.centreon.com/

**Comment by kozfelipe** [comment]
Thank you @ponchoh 
My analyst forgot the template. Sorry for the inconvenience
