### ISSUE TITLE
Centreon 22.04 on Raspberry Pi (ARM64)

### ISSUE THREAD

**Issue by naziris** [centreon-archive/centreon-archived#11682]
Hello,

I managed to install Centreon 21.10 on a Raspberry Pi following [this](https://www.sugarbug.fr/framboise/full_raspcentreon4_2110/) guide.

I've done several attempts but I always fail to login following with the same "Token" error as you can see from the screenshot.
![Screenshot 2022-06-19 135548](https://user-images.githubusercontent.com/5808427/188259998-74db7232-854a-4cd8-85b9-22ab431f4356.png)

I don't have any error logs unfortunately cause I wiped my Pi once again, but I will reinstall, reproduce the issue and attached the error logs.

Any first thoughts regarding this issue? anyone faced it before?

**Comment by kozfelipe** [comment]
Internal Server Error 500 - You should check your php-fpm centreon-error.log

**Comment by ponchoh** [comment]
@naziris 

You should update your apache 

10-centreon.conf


and make sure you have

```
Header always edit Set-Cookie ^(.*)$ $1;HttpOnly
```

or a proper one according to your setup, restart apache and you should be good to go

# 🤞

**Comment by naziris** [comment]
Thank you @ponchoh! Your solution was the one.
