### ISSUE TITLE
Alcatel Stack wrong OID

### ISSUE THREAD

**Issue by c0c0163** [centreon-archive/centreon-archived#11739]
Alcatel switch are not defined as a stack but as a chassis.

Consequently, the OID: .1.3.6.1.2.1.47.1.1.1.1.5 (entPhysicalClass) will always appear as chassis(3).
This leads to the plugin centreon_alcatel_omniswitch_snmp.pl to never check the stack.

Alcatel is using a dedicate MIB (ALCATEL-IND1-VIRTUAL-CHASSIS-MIB) for the virtual chassis which is under the following table:
.1.3.6.1.4.1.6486.801.1.2.1.69.1.1.2

Could you please amend the plugin accordingly?

**Comment by garnier-quentin** [comment]
Could you provide the MIB and the snmpwalk of the branch: .1.3.6.1.4.1.6486.801.1.2.1.69.1.1.2 ? You should post it in centreon-plugins project

**Comment by c0c0163** [comment]
Moved to centreon-plugin
https://github.com/centreon/centreon-plugins/issues/3896
