### ISSUE TITLE
Service Template display error

### ISSUE THREAD

**Issue by jloggia1** [centreon-archive/centreon-archived#11775]
### Description

The parent of service templates is not being display correct for Centreon version => 21.10.9.

![image](https://user-images.githubusercontent.com/107404891/190600972-048ac324-d4f0-4998-b3ba-56a5aa3be0af.png)

It seems like this is caused by the new function in /usr/share/centreon/www/include/configuration/configObject/service_template_model/listServiceTemplateModel.php line 235:

`"RowMenu_parent" => htmlentities($tplStr)`

If you replace this line with a function of a previous version, everything works fine.

`"RowMenu_parent" => CentreonUtils::escapeSecure($tplStr)`

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. Have a Centreon Version >=21.10.9
2. Go to Services -> Templates 
3. Check the "Templates" column

**Comment by ponchoh** [comment]
https://github.com/centreon/centreon/commit/00b808aa5e9c1f41b47b8daf87642810d948ec4b
