### ISSUE TITLE
No parent platform was found for : 'poller-1'

### ISSUE THREAD

**Issue by mooky31** [centreon-archive/centreon-archived#11852]
Hello,

I'm trying to deloy a poller on a lab environment.
The central and the poller are on the same LAN, no firewalls.

Central and poller are both 21.10.10.

I followed carefully this doc : https://docs.centreon.com/fr/docs/21.10/installation/installation-of-a-poller/using-centreon-iso/
When I try to register the poller, here is what I get: 
```
[root@poller1 ~]# /usr/share/centreon/bin/registerServerTopology.sh -u admin -t poller -h 192.168.30.14 -n poller-1
Please enter the password of 192.168.30.14:

  Summary of the information that will be send:

  Api Connection:
  username: admin
  password: ******
  target server: 192.168.30.14

  Pending Registration Server:
  name: poller-1
  hostname: poller1
  type: poller
  address: 192.168.30.20

Do you want to register this server with those information? (y/n): y
2022-09-22 14:25:33+02:00 - ERROR - http://192.168.30.14:80: {"message":"No parent platform was found for : 'poller-1'@'192.168.30.20'"}

```

Is there a bug ? Or am I doing something wrong ?

Thank you

**Comment by mooky31** [comment]
Found it : my central server was referenced as 127.0.0.1 in pollers list.
I changed its IP to 192.168.30.14 and it works.

**Comment by ponchoh** [comment]
Thank you for the update.

**Comment by mooky31** [comment]
While I'm here : the poller wizard fails silently if resource $USER1$ doesn't exist
