### ISSUE TITLE
Change name of curve in RRD graph for meta service

### ISSUE THREAD

**Issue by ghost** [centreon-archive/centreon-archived#1599]
---

Author Name: **Laurent Pinsivy** (Laurent Pinsivy)
Original Redmine Issue: 957, https://forge.centreon.com/issues/957
Original Date: 2009-06-05

---

Change curve named "value" by the name of metric used.

**Comment by kozfelipe** [comment]
can we at least style "value"?

**Comment by Sims24** [comment]
may you can take a look at virtualservice mode on centreon-plugins project, it might achieve what you want

**Comment by kozfelipe** [comment]
@Sims24 great thanks for advice
