### ISSUE TITLE
Plantage du processus Centcore et non traitement des traps

### ISSUE THREAD

**Issue by ghost** [centreon-archive/centreon-archived#1951]
---

Author Name: **Hyper Visor** (Hyper Visor)
Original Redmine Issue: 5036, https://forge.centreon.com/issues/5036
Original Date: 2013-12-10
Original Assignee: Julien Mathis

---

Bonjour,

Je suis en Centreon 2.3.9 et je rencontre des problèmes avec Centcore. Le processus semble planter. Voici les symptomes:

Lorsque je fais un /etc/init.d/centcore status, le processus est démarré, mais lorsque je regarde le fichier de log, rien ne se passe, même quand je génère des traps avec snmptrap. J'essaie de faire un restart de Centcore, impossible, je suis obligé de killer le process et de supprimer  centcore.pid avant de redémarrer.

Les conséquences de ce plantage et que je n'ai plus de trap qui s'affiche dans Centreon web, snmptt fait bien son boulot et snmptraphandler aussi. Je suis obligé de redémarrer le process Centcore, j'ai trouvé une solution de contournement, avec un eventhandlers qui redémarre le process lorsque je remarque que les traps ne sont plus traitées (avec des trap test dans un cron) mais ce n'est pas super propre...

Est-ce un problème connu ?

J'ai joint mes binaires Centcore et centTrapHandler.

**Comment by Fourier1** [comment]
j'ai le même problème , lorsque je fait les acquittement , 
('requests text : ', u'"Cannot open Centcore file"')
('requests json : ', <bound method Response.json of <Response [200]>>)

et l’acquittement ne s'effectue pas

**Comment by lpinsivy** [comment]
@Fourier1 can you open a new ticket because this one is really old
