### ISSUE TITLE
optional Embedded perl

### ISSUE THREAD

**Issue by ghost** [centreon-archive/centreon-archived#3032]
---

Author Name: **Raphael Troiano** (Raphael Troiano)
Original Redmine Issue: 4344, https://forge.centreon.com/issues/4344
Original Date: 2013-03-26
Original Assignee: Sylvestre Ho

---

Hi,

On centreon 2.4.1 install with engine, there is no p1.pl file.
The web install block if i don't set a true p1.pl file.

I ve restore an old nagios p1.pl file but it should be really optional.

Thx,

**Comment by hecko** [comment]
The documentation states 

`Location of the Perl program to provide Perl code persistence for the Monitoring Engine project. This program provides an API for calling Monitoring Engine Perl plugins from Monitoring Engine when it is built with embedded Perl support. The intent is to tradeoff memory usage against repeated context switches to recompile Perl plugins. **The file p1.pl is provided by default with the Monitoring Engine package.**`

But could not find the p1.pl file anywhere in any packages:

[root@SDCTLP0009 ~]# yum provides "*/p1.pl"

This is probably just a cosmetic thing, but Im getting (2.7.1) this when generating config for a poller: 
Warning p1_file variable ignored
Warning enable_embedded_perl variable ignored
Warning use_embedded_perl_implicitly variable ignored
