### ISSUE TITLE
Database Error: Could not connect to database.  Please contact your administrator.

### ISSUE THREAD

**Issue by Elikha** [centreon-archive/centreon-archived#6494]
I have waked up today and on the interface of centreon i've seen an error on centreon interface "Database Error: Could not connect to database.  Please contact your administrator." and the result of command df is
[root@centreonSRVBDD mysql]# df
Filesystem           1K-blocks     Used Available Use% Mounted on
/dev/mapper/vg_centreonsrvbdd-lv_root
                      51475068 48837324     16304 100% /
tmpfs                  4030508        0   4030508   0% /dev/shm
/dev/sda1               487652    58454    403598  13% /boot
/dev/mapper/vg_centreonsrvbdd-lv_home
                     358570748    77992 340271700   1% /home

So I seek help, best regards.

**Comment by RymRabehi** [comment]
Hi,

Your / partition seems to be full. You should make some place or extend the partition.

Rym R.
